// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Banco descartável que o Prisma usa para conferir o efeito das migrações
    // antes de aplicá-las. Só é preciso em desenvolvimento, ao gerar migração
    // nova — `migrate deploy`, que é o que roda na VPS, não o usa.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
